### PR TITLE
Configure logging

### PR DESCRIPTION
**Pull request by rjkip**
prod: syslog (ident conext-operations-support)
test: stream to app/logs/test.log
dev:  syslog, CLI (-v=NOTICE, -vv=INFO, -vvv=DEBUG)

https://www.pivotaltracker.com/story/show/104932684

### CODE REVIEW

**Comment by rjkip** [comment]
`PING` @DRvanR @arothuis

**Comment by DRvanR** [comment]
waddabout acceptance envs?

**Comment by DRvanR** [comment]
other than that, :+1:

**Comment by arothuis** [comment]
:banana: :banana: :+1:

**Pull request merged**
